/** 100 fortune-cookie teasers. One picked at random on every page load. */
export const FORTUNES = [
  "The glow lasts longer if you take your time.",
  "A soft launch begins with soft light.",
  "Your next favorite shade is already waiting.",
  "Tonight the shelves dream of you.",
  "Patience is a good primer.",
  "Something yellow is about to happen.",
  "A quiet corner holds a loud idea.",
  "Trust the second swipe.",
  "Beauty loves a slow walk past the gondola.",
  "You will find the good stuff under soft light.",
  "A small ritual fixes a long day.",
  "The mirror is kinder after 9pm.",
  "Keep a pocket for surprises.",
  "Your skin remembers good habits.",
  "Someone left a hint on the endcap.",
  "The best aisle is the one you wander twice.",
  "Warm light finds warm people.",
  "A little gloss goes a long way.",
  "Tomorrow likes what you start tonight.",
  "The mall will hush. You will glow.",
  "Curiosity is the best accessory.",
  "A closed shutter opens a dream.",
  "You are one good scent away from a mood shift.",
  "The tester table knows your name.",
  "Soft brown holds a strong opinion.",
  "Leave room for a spontaneous add-on.",
  "Your playlist and your palette should match.",
  "A tiny bottle can change the whole cart.",
  "The cream background is doing more than you think.",
  "Good things come in refillable packages.",
  "You will notice the yellow first.",
  "A friendly stranger recommends the hero SKU.",
  "Night air is good for big ideas.",
  "The floor plan is a love letter in metres.",
  "Your next compliment is already in stock.",
  "Stay for one more bay.",
  "The Barrisol hums approval.",
  "A clean lip line solves three problems.",
  "You are early to something nice.",
  "The queue is short because patience is fashionable.",
  "A glow-up can be quiet.",
  "Trust the beige more than the hype.",
  "Your cart wants one more treat.",
  "The endcap is telling a joke. Laugh.",
  "Soft focus, hard standards.",
  "A scrawl on the wall is a map.",
  "You will leave smelling like a better day.",
  "The night shift of beauty never really clocks out.",
  "Something cute is about to yoink your attention.",
  "A small sparkle is still a sparkle.",
  "The brand yellow is a weather report: sunny.",
  "You are allowed to take the scenic shelf.",
  "A good serum does not shout.",
  "The dollhouse view sees you smiling.",
  "Keep your receipts and your rituals.",
  "The next trend is already on the mask wall.",
  "A soft wipe cleans a hard day.",
  "You will find joy in the middle bay.",
  "The lighting was designed for your cheekbones.",
  "A short visit can be a long memory.",
  "Cream walls make brave choices easier.",
  "Your future self thanks you for SPF.",
  "The gondola has a secret favorite.",
  "A wink from the lightbox means go.",
  "You are exactly on time for magic.",
  "The scent trail leads somewhere kind.",
  "A tidy bag makes room for fun.",
  "Brown ink writes soft promises.",
  "The store is quieter than your thoughts. Listen.",
  "A sample is a preview of courage.",
  "You will choose the one that feels like home.",
  "The after-hours air is a filter.",
  "A little blue cools a warm mood.",
  "Your reflection practices being delighted.",
  "The hero product was waiting for this exact you.",
  "A slow scroll of the shelf beats a rush.",
  "You are invited to linger.",
  "The pattern on the wall likes company.",
  "A clean brush starts a clean chapter.",
  "Your luck smells faintly of citrus and hope.",
  "The checkout corner has room for wonder.",
  "A soft yes is still a yes.",
  "You will leave with less worry and more glow.",
  "The night is a good customer.",
  "A sticker on the mirror says try again tomorrow.",
  "Your taste is trending in this aisle.",
  "The warm key light flatters everyone tonight.",
  "A small purchase can be a big mood.",
  "You are the main character of this quiet floor.",
  "The scrawl says: more joy, less hurry.",
  "A closed door means a private preview.",
  "Your hands will find the right jar.",
  "The cream field is a blank page. Write softly.",
  "A fortune without glitter is still shiny.",
  "You will come back for the feeling, not the receipt.",
  "The shelves rearrange themselves for destiny.",
  "A gentle routine beats a loud one.",
  "Your glow has RSVP'd yes.",
  "The Bugis night air keeps secrets well.",
  "Something lovely is already in motion.",
];

export function pickFortune() {
  return FORTUNES[Math.floor(Math.random() * FORTUNES.length)];
}
